<a href="https://colab.research.google.com/github/Escalada-Matthew/CPE-311/blob/main/hoa6_1_Escalada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Hands-on Activity 6.1 Introduction to Data Analysis and Tools**

CPE311 Computational Thinking with Python
<br> Name: Escalada, Lhei Matthew <br>
Section: CPE22S3
<br> Performed on:02/12/2026 <br>
Submitted on: 02/12/2026
<br>Submitted to: Engr. Neal James Barton Matira<br>

In [ ]:
#Exercise 1 & 2
#Run the given code below and perform the given tasks without any python modules
import random
random.seed(0)
salaries = [round(random.random()*1000000, -3) for _ in range(100)]

**Exercise 1. Using the data generated above, calculate the following statistics without importing anything from the statistics module in the standard library**

In [ ]:

#1. Mean
mean = sum(salaries) / len(salaries)
print("Mean:", {mean})
#2. Median
sort = sorted(salaries)
n = len(sort)
median = (sort[n//2-1] + sort[n//2]) / 2
print("Median:", {median})
#3. Mode
map_values = {}
for salary in salaries:
  if salary not in map_values:
    map_values[salary] = 1
    continue
  map_values[salary] += map_values[salary] + 1

mode = max(map_values, key=map_values.get)
print("Mode:", {mode}, "Repeated", max(map_values.values()), "times")

Mean: {585690.0}
Median: {589000.0}
Mode: {477000.0} Repeated 7 times

In [ ]:
#4. Sample Variance
n = len(salaries)
sumresult = sum((x - mean)**2 for x in salaries)
variance = sumresult / (n - 1)
print("Sample Variance:", {variance})
#5. Sample Standard Deviation
standard_deviation = variance ** 0.5
print("Sample Standard Deviation:", {standard_deviation})

Sample Variance: {70664054444.44444}
Sample Standard Deviation: {265827.11382484}

**Exercise 2.
Using the same data, calculate the following statistics using the functions in the statistics module where appropriate**

In [ ]:

import statistics

#1. Range
range = max(salaries) - min(salaries)
print(f"Range: {max(salaries)} - {min(salaries)} = {range}")

Range: 996000.0 - 1000.0 = 995000.0

In [ ]:

#2. Interquartile Range
q1, q2, q3 = statistics.quantiles(salaries, n=4)
iqr = q3 - q1

#3. Coefficient of Variation
coef_variation = (statistics.stdev(salaries) / statistics.mean(salaries)) * 100

#4. Quartile Coefficient of Dispersion
qcd = (q3 - q1) / (q3 + q1)

print("Interquartile Range:", {iqr})
print("Coefficient of Variation:", {coef_variation})
print("Quartile Coefficient of Dispersion:", {qcd})

Interquartile Range: {421750.0}
Coefficient of Variation: {45.38699889443903}
Quartile Coefficient of Dispersion: {0.34491923941934166}

**Exercise 3: Pandas for Data Analysis
Load the diabetes.csv file. Convert the diabetes.csv into dataframe**

In [4]:
#Perform the following tasks in the diabetes dataframe:
import pandas as pd

diabetes = pd.read_csv('diabetes.csv')
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
#1. Identify the column names
diabetes.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [5]:
#2. Identify the data types of the data
diabetes.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [6]:
#3. Display the total number of records
len(diabetes)

768

In [7]:
#4. Display the first 20 records
diabetes.head(20)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
11,10,168,74,0,0,38.0,0.537,34,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
15,7,100,0,0,0,30.0,0.484,32,1
16,0,118,84,47,230,45.8,0.551,31,1
17,7,107,74,0,0,29.6,0.254,31,1
18,1,103,30,38,83,43.3,0.183,33,0
19,1,115,70,30,96,34.6,0.529,32,1

In [8]:
#5. Display the last 20 records
diabetes.tail(20)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
748,3,187,70,22,200,36.4,0.408,36,1
749,6,162,62,0,0,24.3,0.178,50,1
750,4,136,70,0,0,31.2,1.182,22,1
751,1,121,78,39,74,39.0,0.261,28,0
752,3,108,62,24,0,26.0,0.223,25,0
753,0,181,88,44,510,43.3,0.222,26,1
754,8,154,78,32,0,32.4,0.443,45,1
755,1,128,88,39,110,36.5,1.057,37,1
756,7,137,90,41,0,32.0,0.391,39,0
757,0,123,72,0,0,36.3,0.258,52,1
758,1,106,76,0,0,37.5,0.197,26,0
759,6,190,92,0,0,35.5,0.278,66,1
760,2,88,58,26,16,28.4,0.766,22,0
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [9]:
#6. Change the Outcome column to Diagnosis
diabetes = diabetes.rename(columns={'Outcome':'Diagnosis'})
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Diagnosis
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [16]:
#7. Create a new column Classification that display "Diabetes" if the value of outcome is 1 , otherwise "No Diabetes"
diabetes['Classification'] = diabetes['Diagnosis'].apply(lambda x: 'Has Diabetes' if x == 1 else 'No Diabetes')
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Diagnosis,Classification
0,6,148,72,35,0,33.6,0.627,50,1,Has Diabetes
1,1,85,66,29,0,26.6,0.351,31,0,No Diabetes
2,8,183,64,0,0,23.3,0.672,32,1,Has Diabetes
3,1,89,66,23,94,28.1,0.167,21,0,No Diabetes
4,0,137,40,35,168,43.1,2.288,33,1,Has Diabetes

In [17]:
#8. Create a new dataframe "withDiabetes" that gathers data with diabetes
withDiabetes = diabetes[diabetes['Classification'] == 'Has Diabetes']
withDiabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Diagnosis,Classification
0,6,148,72,35,0,33.6,0.627,50,1,Has Diabetes
2,8,183,64,0,0,23.3,0.672,32,1,Has Diabetes
4,0,137,40,35,168,43.1,2.288,33,1,Has Diabetes
6,3,78,50,32,88,31.0,0.248,26,1,Has Diabetes
8,2,197,70,45,543,30.5,0.158,53,1,Has Diabetes

In [18]:
#9. Create a new dataframe "noDiabetes" thats gathers data with no diabetes
withoutDiabetes = diabetes[diabetes['Classification'] == 'No Diabetes']
withoutDiabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Diagnosis,Classification
1,1,85,66,29,0,26.6,0.351,31,0,No Diabetes
3,1,89,66,23,94,28.1,0.167,21,0,No Diabetes
5,5,116,74,0,0,25.6,0.201,30,0,No Diabetes
7,10,115,0,0,0,35.3,0.134,29,0,No Diabetes
10,4,110,92,0,0,37.6,0.191,30,0,No Diabetes

In [19]:
#10. Create a new dataframe "Pedia" that gathers data with age 0 to 19
Pedia = diabetes[diabetes['Age'] <= 19]
Pedia.head()

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Diagnosis, Classification]
Index: []

In [20]:
#11. Create a new dataframe "Adult" that gathers data with age greater than 19
Adult = diabetes[diabetes['Age'] > 19]
Adult.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Diagnosis,Classification
0,6,148,72,35,0,33.6,0.627,50,1,Has Diabetes
1,1,85,66,29,0,26.6,0.351,31,0,No Diabetes
2,8,183,64,0,0,23.3,0.672,32,1,Has Diabetes
3,1,89,66,23,94,28.1,0.167,21,0,No Diabetes
4,0,137,40,35,168,43.1,2.288,33,1,Has Diabetes

In [ ]:
#12. Use numpy to get the average age and glucose value.

In [ ]:
#13. Use numpy to get the median age and glucose value.

In [ ]:
#14. Use numpy to get the middle values of glucose and age.

In [23]:
import numpy as np

#12. Use numpy to get the average age and glucose value.
avg_age = diabetes['Age'].mean()
avg_glucose = diabetes['Glucose'].mean()

#13. Use numpy to get the median age and glucose value.
#14. Use numpy to get the middle values of glucose and age.
#I think it's the same?
diabetes.sort_values(by='Age')

median_age = diabetes['Age'].median()
median_glucose = diabetes['Glucose'].median()

#15. Use numpy to get the standard deviation of the skinthickness.
standard_skin = diabetes['SkinThickness'].std()


print(f"Average age: {avg_age}, Average Glucose Value: {avg_glucose}")
print(f'Median age: {median_age}, Median Glucose Value: {median_glucose}')
print(f'Middle age: {median_age}, Middle glucose: {median_glucose}')
print(f'Skin Thickness STD: {standard_skin}')

Average age: 33.240885416666664, Average Glucose Value: 120.89453125
Median age: 29.0, Median Glucose Value: 117.0
Middle age: 29.0, Middle glucose: 117.0
Skin Thickness STD: 15.952217567727677

<br>**Conclusion**<br>
During this activity, I was able to demonstrate how to do mean, median, mode, variance, and standard deviation without the use of numpy. I was also able to further familiarize myself with using pandas and numpy in sorting and analyzing datasets during Exercise 3.